MODEL:
  META_ARCHITECTURE: 'IDIP'
  MASK_ON: True
  PIXEL_MEAN: [ 123.675, 116.280, 103.530 ]
  PIXEL_STD: [ 58.395, 57.120, 57.375 ]
  BACKBONE:
    NAME: 'build_resnet_fpn_backbone'
  RESNETS:
    OUT_FEATURES: [ 'res3', 'res4', 'res5' ]
    STRIDE_IN_1X1: False
  FPN:
    IN_FEATURES: [ 'res3', 'res4', 'res5' ]
  ROI_HEADS:
    IN_FEATURES: [ 'p3', 'p4', 'p5' ]
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
  ROI_MASK_HEAD:
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
SOLVER:
  WARMUP_FACTOR: 0.01
  OPTIMIZER: 'ADAMW'
  IMS_PER_BATCH: 12
  BASE_LR: 0.00005
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: 'full_model'
DATASETS:
  TRAIN: ('coco_2017_train',)
  TEST: ('coco_2017_val',)
SEED: 42
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  CROP:
    ENABLED: True
    TYPE: 'absolute_range'
    SIZE: (384, 600)
  FORMAT: 'RGB'
  MASK_FORMAT: 'bitmask'
TEST:
  EVAL_PERIOD: 5000
VERSION: 2